import { constants } from 'node:fs'
import { open, realpath, stat } from 'node:fs/promises'
import type { FileHandle } from 'node:fs/promises'
import { isAbsolute, relative, resolve, sep } from 'node:path'
import { TextDecoder } from 'node:util'

const utf8Decoder = new TextDecoder('utf-8', { fatal: true })

/** Inputs assembled after a repository is initialized for Trellis. */
export interface TrellisContextInput {
  /** Repository-analysis workflow that must run before specification bootstrap. */
  codegraphWorkflow: string
  /** Workflow generated by the Trellis initializer for this repository. */
  bootstrapSkill: string
  /** Git workflow that applies after specification bootstrap. */
  postBootstrapWorkflow: string
}

/** Assemble the mandatory repository-analysis and bootstrap instructions. */
export function trellisContextText(input: TrellisContextInput): string {
  return [
    '## Trellis repository bootstrap',
    'Use CodeGraph as the repository-analysis input for this task.',
    input.codegraphWorkflow.trim(),
    'Complete the generated `trellis-spec-bootstrap` Skill before working on the original request.',
    'If the Skill is not discoverable, read it directly from `$project_root/.claude/skills/trellis-spec-bootstrap/SKILL.md`.',
    input.bootstrapSkill.trim(),
    '## Post-bootstrap Git workflow',
    input.postBootstrapWorkflow.trim(),
  ].join('\n\n')
}

function contained(root: string, candidate: string): boolean {
  const path = relative(root, candidate)
  return path === '' || (!path.startsWith(`..${sep}`) && path !== '..' && !isAbsolute(path))
}

function sameFile(
  left: Awaited<ReturnType<FileHandle['stat']>>,
  right: Awaited<ReturnType<FileHandle['stat']>>,
): boolean {
  return left.dev === right.dev && left.ino === right.ino
}

/** An opened regular file whose descriptor identity and containment were validated once. */
export class ContainedFile {
  private constructor(private readonly handle: FileHandle) {}

  /**
   * Open a pathname without following its final component and bind reads to the validated descriptor.
   * @param containmentRoot - Directory that must canonically contain the opened descriptor.
   * @param path - Lexical pathname to open.
   * @returns An owned descriptor that the caller must close.
   */
  static async open(containmentRoot: string, path: string): Promise<ContainedFile> {
    const lexicalRoot = resolve(containmentRoot)
    const canonicalRoot = await realpath(containmentRoot)
    const lexicalPath = resolve(path)
    if (!contained(lexicalRoot, lexicalPath)) throw new Error(`file escapes containment root: ${path}`)

    const handle = await open(lexicalPath, constants.O_RDONLY | constants.O_NOFOLLOW)
    try {
      const descriptor = await handle.stat()
      if (!descriptor.isFile()) throw new Error(`file is not regular: ${path}`)
      const canonicalPath = await realpath(lexicalPath)
      if (!contained(canonicalRoot, canonicalPath)) throw new Error(`file escapes containment root: ${path}`)
      const pathname = await stat(canonicalPath)
      if (!sameFile(descriptor, pathname)) throw new Error(`file changed while opening: ${path}`)
      return new ContainedFile(handle)
    } catch (error) {
      await handle.close()
      throw error
    }
  }

  /**
   * Read the complete validated descriptor as fatal UTF-8.
   * @param signal - Caller cancellation signal.
   * @returns Exact descriptor text.
   */
  async readUtf8(signal: AbortSignal): Promise<string> {
    return utf8Decoder.decode(await this.handle.readFile({ signal }))
  }

  /**
   * Read the complete validated descriptor without transforming its bytes.
   * @param signal - Caller cancellation signal.
   * @returns Exact descriptor bytes.
   */
  readBytes(signal: AbortSignal): Promise<Buffer> {
    return this.handle.readFile({ signal })
  }

  /** Close the owned descriptor. */
  close(): Promise<void> {
    return this.handle.close()
  }
}

/**
 * Open one validated contained descriptor.
 * @param containmentRoot - Directory that must canonically contain the opened descriptor.
 * @param path - Lexical pathname to open without following its final component.
 * @returns An owned descriptor that the caller must close.
 */
export function openContainedFile(containmentRoot: string, path: string): Promise<ContainedFile> {
  return ContainedFile.open(containmentRoot, path)
}
